
import { createCardState, useCard, getWildHorseMoves, getCardName, getCardDescription } from "./cards.js";

window.onerror = msg => alert("에러: " + msg);

const Game = (() => {
  const SERVER = location.protocol === "https:" ? `wss://${location.host}` : `ws://${location.host}`;

  let ws=null, board=[], turn="white", selected=null, moves=[], localMode=true, myColor=null, roomCode=null;
  let enPassant=null, touchFrom=null, ghost=null, promotionResolve=null;
  let playerName=localStorage.getItem("randomChessName")||"", pendingJoinRoom=null;
  let moved={wk:false,wrA:false,wrH:false,bk:false,brA:false,brH:false};
  let myCard=null, cardState=createCardState(), pendingCardUse=null;
  let equalityUses={white:0,black:0};

  const imgs={
    wp:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/wp.png",
    wr:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/wr.png",
    wn:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/wn.png",
    wb:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/wb.png",
    wq:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/wq.png",
    wk:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/wk.png",
    bp:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/bp.png",
    br:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/br.png",
    bn:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/bn.png",
    bb:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/bb.png",
    bq:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/bq.png",
    bk:"https://images.chesscomfiles.com/chess-themes/pieces/neo/150/bk.png"
  };

  function createBoard(){return [["br","bn","bb","bq","bk","bb","bn","br"],["bp","bp","bp","bp","bp","bp","bp","bp"],["","","","","","","",""],["","","","","","","",""],["","","","","","","",""],["","","","","","","",""],["wp","wp","wp","wp","wp","wp","wp","wp"],["wr","wn","wb","wq","wk","wb","wn","wr"]]}
  function squareName(r,c){return `${String.fromCharCode(97+c)}${8-r}`}
  function closeAllCardModals(){["necroModal","exorcismModal","reactionaryModal","spaceModal","passwordModal"].forEach(id=>document.getElementById(id)?.classList.add("hidden"))}
  function resetState(){board=createBoard();turn="white";selected=null;moves=[];enPassant=null;touchFrom=null;pendingJoinRoom=null;moved={wk:false,wrA:false,wrH:false,bk:false,brA:false,brH:false};cardState=createCardState();pendingCardUse=null;equalityUses={white:0,black:0};closeAllCardModals()}
  function cancelCardSelection(){closeAllCardModals();pendingCardUse=null;cardState.activeMode=null;cardState.selectedSquares=[];selected=null;moves=[];renderCard();render()}
  function ensureLogin(){if(!playerName){const v=document.getElementById("nicknameInput")?.value.trim();if(v){playerName=v.slice(0,20);localStorage.setItem("randomChessName",playerName)}}if(!playerName){alert("먼저 닉네임으로 로그인해라.");return false}const s=document.getElementById("loginStatus");if(s)s.textContent=`${playerName} 로그인됨`;return true}
  function loginNickname(){const v=document.getElementById("nicknameInput").value.trim();if(!v)return alert("닉네임을 입력해라.");playerName=v.slice(0,20);localStorage.setItem("randomChessName",playerName);document.getElementById("loginStatus").textContent=`${playerName} 로그인됨`;alert("닉네임 로그인 완료")}
  function loginGoogle(){alert("Google 로그인은 Firebase 설정값 넣은 뒤 연결 가능함. 지금은 닉네임 로그인 쓰면 됨.")}
  function connectLobbySocket(onOpen){if(ws&&ws.readyState===WebSocket.OPEN){onOpen?.();return}if(ws)ws.close();ws=new WebSocket(SERVER);ws.onopen=()=>onOpen?.();ws.onerror=()=>alert("서버 연결 에러");ws.onclose=()=>console.log("서버 연결 끊김");ws.onmessage=handleSocketMessage}
  function createOnlineRoom(){if(!ensureLogin())return;const name=document.getElementById("roomNameInput").value.trim(),password=document.getElementById("roomPasswordInput").value,priv=document.getElementById("privateRoomCheck").checked;if(!name)return alert("방 이름을 입력해라.");localMode=false;connectLobbySocket(()=>ws.send(JSON.stringify({type:"createRoom",name,password,private:priv,playerName})))}
  function refreshRooms(){if(!ensureLogin())return;connectLobbySocket(()=>ws.send(JSON.stringify({type:"listRooms"})))}
  function renderRoomList(listData){const list=document.getElementById("roomList");if(!list)return;if(!listData||listData.length===0){list.innerHTML="<p>열려있는 공개방이 없습니다.</p>";return}list.innerHTML="";listData.forEach(room=>{const div=document.createElement("div");div.className="roomItem";div.innerHTML=`<div class="roomItemTitle">${room.name}</div><div class="roomItemInfo">방장: ${room.hostName}<br>인원: ${room.players}/${room.maxPlayers}<br>상태: ${room.hasPassword?`<span class="roomLocked">비밀번호 필요</span>`:`<span class="roomOpen">바로 입장 가능</span>`}<br>초대코드: ${room.id}</div><button>입장</button>`;div.querySelector("button").onclick=()=>room.hasPassword?openPasswordModal(room.id,room.name):joinRoom(room.id,"");list.appendChild(div)})}
  function openPasswordModal(id,name){pendingJoinRoom=id;document.getElementById("passwordRoomTitle").textContent=`${name} 입장`;document.getElementById("passwordModalInput").value="";document.getElementById("passwordModal").classList.remove("hidden")}
  function submitRoomPassword(){if(!pendingJoinRoom)return;const pw=document.getElementById("passwordModalInput").value;document.getElementById("passwordModal").classList.add("hidden");joinRoom(pendingJoinRoom,pw);pendingJoinRoom=null}
  function cancelPasswordModal(){pendingJoinRoom=null;document.getElementById("passwordModal").classList.add("hidden")}
  function joinByInviteCode(){if(!ensureLogin())return;const code=document.getElementById("inviteCodeInput").value.trim().toUpperCase(),pw=document.getElementById("invitePasswordInput").value;if(!code)return alert("초대코드를 입력해라.");joinRoom(code,pw)}
  function joinRoom(id,password=""){if(!ensureLogin())return;localMode=false;roomCode=id;connectLobbySocket(()=>ws.send(JSON.stringify({type:"join",roomId:id,password,playerName})))}
  function copyInviteCode(){if(!roomCode)return alert("현재 온라인 방이 아닙니다.");navigator.clipboard?.writeText(roomCode).then(()=>alert("초대코드 복사됨: "+roomCode)).catch(()=>alert("초대코드: "+roomCode))}
  function showGame(){document.getElementById("menu").classList.add("hidden");document.getElementById("game").classList.remove("hidden")}
  function backMenu(){removeGhost();closeAllCardModals();document.getElementById("game").classList.add("hidden");document.getElementById("menu").classList.remove("hidden")}
  function status(t){document.getElementById("status").textContent=t}
  function startLocal(){localMode=true;myColor=null;roomCode=null;myCard=null;resetState();showGame();renderCard();render()}

  function handleSocketMessage(e){
    const data=JSON.parse(e.data);
    if(data.type==="roomCreated"){roomCode=data.roomId;joinRoom(data.roomId,document.getElementById("roomPasswordInput").value);return}
    if(data.type==="roomList"){renderRoomList(data.rooms);return}
    if(data.type==="wrongPassword"){alert(data.message||"비밀번호가 틀렸습니다.");return}
    if(data.type==="waiting"){roomCode=data.roomId||roomCode;showGame();status(`${data.roomName||roomCode} / 상대 기다리는 중... / 초대코드: ${roomCode}`);document.getElementById("board").innerHTML="";renderCard();return}
    if(data.type==="start"){roomCode=data.roomId||roomCode;myCard=data.card;myColor=data.color;board=data.board;turn=data.turn;enPassant=data.enPassant||null;moved=data.moved||moved;if(data.capturedPieces)cardState.necroCapturedPieces=data.capturedPieces;if(data.spaceTravelEnabled!==undefined)cardState.spaceTravelEnabled=data.spaceTravelEnabled;if(data.equalityUses)equalityUses=data.equalityUses;showGame();renderCard();render();return}
    if(data.type==="update"){board=data.board;turn=data.turn;enPassant=data.enPassant||null;moved=data.moved||moved;if(data.doubleMove&&myColor){cardState.doubleMoveLeft=data.doubleMove[myColor];cardState.doubleMoveActive=cardState.doubleMoveLeft>0}if(data.wildHorse&&myColor)cardState.wildHorse=data.wildHorse[myColor];if(data.kingReturn&&myColor)cardState.kingReturn=data.kingReturn[myColor]||null;if(data.reactionary&&myColor){const r=data.reactionary[myColor];if(r){cardState.reactionaryActive=r.active;cardState.reactionaryRook=r.rook;cardState.reactionaryChecks=r.checks}}if(data.capturedBy&&myColor)cardState.necroCapturedPieces=data.capturedBy[myColor]||[];if(data.spaceTravel&&myColor)cardState.spaceTravelEnabled=!!data.spaceTravel[myColor];if(data.equalityUses)equalityUses=data.equalityUses;if(data.usedCards&&myColor&&data.usedCards[myColor]&&myCard!=="equality"&&myCard!=="reactionary"&&myCard!=="spaceTravel")myCard=null;selected=null;moves=[];removeGhost();renderCard();render();return}
    if(data.type==="reactionaryRequest"){if(data.color)turn=data.color;cardState.activeMode="reactionaryPick";selected=null;moves=data.options||[];alert(data.message||"킹이 잡혔습니다. 반동분자로 왕룩을 선택하세요.");renderCard();render();return}
    if(data.type==="gameover"){board=data.board;removeGhost();render();alert("게임 끝! 승자: "+data.winner);return}
    if(data.type==="full"){alert("방이 가득 참");return}
    if(data.type==="error"){alert(data.message);return}
  }

  function resign(){const winner=turn==="white"?"black":"white";alert("기권! 승자: "+winner);if(!localMode&&ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:"resign"}))}
  function render(){
    const bd=document.getElementById("board");bd.innerHTML="";
    status((localMode?"로컬 2인":`온라인 ${roomCode} / 내 색: ${myColor||"대기중"}`)+` | ${turn} 턴`);
    for(let r=0;r<8;r++)for(let c=0;c<8;c++){
      const cell=document.createElement("div");cell.className="cell "+((r+c)%2===0?"light":"dark");cell.dataset.r=r;cell.dataset.c=c;
      if(selected&&selected.r===r&&selected.c===c)cell.classList.add("selected");
      const legal=moves.find(m=>m.r===r&&m.c===c);
      if(legal){if(legal.type==="equalityCastle")cell.classList.add("equalityCastleMove");else if(board[r][c]||legal.type==="enPassant")cell.classList.add("capture");else cell.classList.add("move")}
      if(cardState.activeMode==="equalityPickA"){const p=board[r]?.[c];if(p&&p[0]===turn[0])cell.classList.add("equalityCastleMove")}
      if(cardState.activeMode==="equalityPickB"&&getEqualityTargets().some(p=>p.r===r&&p.c===c))cell.classList.add("equalityCastleMove");
      if(cardState.activeMode==="exorcism"&&getExorcismBishopOptions().some(p=>p.r===r&&p.c===c))cell.classList.add("exorcismCandidate");
      if(cardState.activeMode==="reactionaryPick"&&getReactionaryRookOptions().some(p=>p.r===r&&p.c===c))cell.classList.add("reactionaryCandidate");
      if(cardState.activeMode==="spacePick"&&getSpaceTravelPieces().some(p=>p.r===r&&p.c===c))cell.classList.add("spaceCandidate");
      if(cardState.activeMode==="necroPlace"&&getNecroPlaceMoves().some(p=>p.r===r&&p.c===c))cell.classList.add("necroPlaceCandidate");
      if(cardState.reactionaryActive&&cardState.reactionaryRook&&cardState.reactionaryRook.r===r&&cardState.reactionaryRook.c===c)cell.classList.add("selected");
      const piece=board[r][c];if(piece){const img=document.createElement("img");img.src=imgs[piece];cell.appendChild(img)}
      cell.onclick=()=>clickCell(r,c);
      cell.ontouchstart=ev=>{if(["exorcism","reactionaryPick","spacePick","spacePlace","necroPlace","equalityPickA","equalityPickB"].includes(cardState.activeMode))return;if(!canSelect(r,c))return;ev.preventDefault();selected={r,c};touchFrom={r,c};moves=getMoves(r,c);render();removeGhost();ghost=document.createElement("img");ghost.src=imgs[board[r][c]];ghost.className="dragGhost";document.body.appendChild(ghost);const t=ev.touches[0];moveGhost(t.clientX,t.clientY)}
      cell.ontouchmove=ev=>{if(!ghost)return;ev.preventDefault();const t=ev.touches[0];moveGhost(t.clientX,t.clientY)}
      cell.ontouchend=ev=>{if(!touchFrom)return;ev.preventDefault();const t=ev.changedTouches[0],el=document.elementFromPoint(t.clientX,t.clientY),target=el?.closest(".cell");removeGhost();if(target)tryMove(touchFrom,{r:Number(target.dataset.r),c:Number(target.dataset.c)});touchFrom=null}
      bd.appendChild(cell)
    }
  }
  function moveGhost(x,y){if(!ghost)return;ghost.style.left=x+"px";ghost.style.top=y+"px"}
  function removeGhost(){if(ghost){ghost.remove();ghost=null}}
  function canSelect(r,c){const p=board[r]?.[c];if(!p)return false;if(p[0]!==turn[0])return false;if(!localMode&&myColor&&p[0]!==myColor[0])return false;return true}
  function clickCell(r,c){
    if(cardState.activeMode==="equalityPickA")return chooseEqualityFirst(r,c);
    if(cardState.activeMode==="equalityPickB")return chooseEqualitySecond(r,c);
    if(cardState.activeMode==="reactionaryPick")return chooseReactionaryRook(r,c);
    if(cardState.activeMode==="spacePick")return chooseSpacePiece(r,c);
    if(cardState.activeMode==="spacePlace")return doSpacePlace(r,c);
    if(cardState.activeMode==="necroPlace")return doNecroPlace(r,c);
    if(cardState.activeMode==="exorcism")return chooseExorcismBishop(r,c);
    if(!selected){if(!canSelect(r,c))return;selected={r,c};moves=getMoves(r,c);render();return}
    tryMove(selected,{r,c})
  }
  function doSpacePlace(r,c){const from=cardState.selectedSquares[0];if(!from)return cancelCardSelection();const piece=board[from.r]?.[from.c],target=board[r]?.[c];if(!piece)return cancelCardSelection();if(target&&target[0]===piece[0])return alert("내 기물이 있는 칸으로는 텔레포트할 수 없습니다.");if(target&&target[1]==="k")return alert("우주여행으로 킹은 잡을 수 없습니다.");if(target&&target[0]!==piece[0])cardState.necroCapturedPieces.push(target);board[r][c]=piece;board[from.r][from.c]="";cardState.selectedSquares=[];cardState.activeMode=null;selected=null;moves=[];turn=turn==="white"?"black":"white";syncCardUpdate();renderCard();render()}
  function doNecroPlace(r,c){if(board[r][c])return alert("빈칸만 가능");const k=findMyKing();if(!k)return alert("킹 없음");if(Math.abs(k.r-r)>1||Math.abs(k.c-c)>1)return alert("킹 주변만 가능");const color=turn[0],type=cardState.necroSelectedPiece[1];board[r][c]=color+type;cardState.necroUsed=true;const i=cardState.necroCapturedPieces.findIndex(p=>p===cardState.necroSelectedPiece);if(i!==-1)cardState.necroCapturedPieces.splice(i,1);cardState.necroSelectedPiece=null;cardState.activeMode=null;selected=null;moves=[];turn=turn==="white"?"black":"white";consumeCurrentCard();syncCardUpdate();renderCard();render()}
  async function tryMove(from,to){const legal=moves.find(m=>m.r===to.r&&m.c===to.c);if(!legal){selected=null;moves=[];touchFrom=null;render();return}let promoteTo=null;const moving=board[from.r][from.c],target=board[to.r][to.c];if(cardState.doubleMoveActive&&cardState.doubleMoveLeft>0&&target&&target[1]==="k"){alert("더블무브 중에는 킹을 잡을 수 없음");selected=null;moves=[];touchFrom=null;render();return}if(moving[1]==="p"&&(to.r===0||to.r===7))promoteTo=await askPromotion();if(localMode){applyMove(from,to,promoteTo);selected=null;moves=[];touchFrom=null;render()}else if(ws&&ws.readyState===WebSocket.OPEN){ws.send(JSON.stringify({type:"move",from,to,promoteTo}));selected=null;moves=[];touchFrom=null;render()}}
  function askPromotion(){document.getElementById("promotionModal").classList.remove("hidden");return new Promise(resolve=>promotionResolve=resolve)}
  function choosePromotion(piece){document.getElementById("promotionModal").classList.add("hidden");if(promotionResolve){promotionResolve(piece);promotionResolve=null}}
  function finishMoveTurn(){if(cardState.doubleMoveLeft>1)cardState.doubleMoveLeft--;else{cardState.doubleMoveLeft=0;cardState.doubleMoveActive=false;turn=turn==="white"?"black":"white"}}
  function applyMove(from,to,promoteTo){const moving=board[from.r][from.c];let captured=board[to.r][to.c];if(captured&&captured[0]!==moving[0]&&captured[1]!=="k")cardState.necroCapturedPieces.push(captured);const legal=getMoves(from.r,from.c).find(m=>m.r===to.r&&m.c===to.c);updateMoved(moving,from);enPassant=null;if(legal?.type==="enPassant"){const capRow=moving[0]==="w"?to.r+1:to.r-1;captured=board[capRow][to.c];if(captured&&captured[0]!==moving[0]&&captured[1]!=="k")cardState.necroCapturedPieces.push(captured);board[capRow][to.c]=""}board[to.r][to.c]=moving;board[from.r][from.c]="";if(legal?.type==="doublePawn"){const dir=moving[0]==="w"?-1:1;enPassant={r:from.r+dir,c:from.c}}if(legal?.type==="castleKing"){const row=moving[0]==="w"?7:0;board[row][5]=board[row][7];board[row][7]=""}if(legal?.type==="castleQueen"){const row=moving[0]==="w"?7:0;board[row][3]=board[row][0];board[row][0]=""}if(moving[1]==="p"&&(to.r===0||to.r===7))board[to.r][to.c]=moving[0]+(promoteTo||"q");if(captured&&captured[1]==="k"){alert("게임 끝! 승자: "+turn);return}if(moving[1]==="k"&&cardState.kingReturn&&cardState.kingReturn.turns>0){cardState.kingReturn.turns--;if(cardState.kingReturn.turns<=0)cardState.kingReturn=null}if(cardState.reactionaryActive&&cardState.reactionaryRook&&cardState.reactionaryRook.r===from.r&&cardState.reactionaryRook.c===from.c)cardState.reactionaryRook={r:to.r,c:to.c};finishMoveTurn()}
  function updateMoved(piece,from){if(piece==="wk")moved.wk=true;if(piece==="bk")moved.bk=true;if(piece==="wr"&&from.r===7&&from.c===0)moved.wrA=true;if(piece==="wr"&&from.r===7&&from.c===7)moved.wrH=true;if(piece==="br"&&from.r===0&&from.c===0)moved.brA=true;if(piece==="br"&&from.r===0&&from.c===7)moved.brH=true}
  function getMoves(r,c){const piece=board[r]?.[c];if(!piece)return[];const color=piece[0],type=piece[1],res=[];const add=(nr,nc,kind="normal")=>{if(nr<0||nr>7||nc<0||nc>7)return;if(!board[nr][nc]||board[nr][nc][0]!==color)res.push({r:nr,c:nc,type:kind})};const slide=dirs=>{for(const[dr,dc]of dirs){let nr=r+dr,nc=c+dc;while(nr>=0&&nr<8&&nc>=0&&nc<8){if(!board[nr][nc])res.push({r:nr,c:nc,type:"normal"});else{if(board[nr][nc][0]!==color)res.push({r:nr,c:nc,type:"normal"});break}nr+=dr;nc+=dc}}};if(type==="p"){const dir=color==="w"?-1:1,start=color==="w"?6:1;if(!board[r+dir]?.[c])add(r+dir,c);if(r===start&&!board[r+dir]?.[c]&&!board[r+dir*2]?.[c])add(r+dir*2,c,"doublePawn");for(const dc of[-1,1]){const target=board[r+dir]?.[c+dc];if(target&&target[0]!==color)add(r+dir,c+dc);if(enPassant&&enPassant.r===r+dir&&enPassant.c===c+dc)res.push({r:r+dir,c:c+dc,type:"enPassant"})}}if(type==="n"){if(cardState.wildHorse)return getWildHorseMoves(r,c,board,color);[[2,1],[1,2],[-1,2],[-2,1],[-2,-1],[-1,-2],[1,-2],[2,-1]].forEach(([dr,dc])=>add(r+dr,c+dc))}if(type==="b")slide([[1,1],[1,-1],[-1,1],[-1,-1]]);if(type==="r")slide([[1,0],[-1,0],[0,1],[0,-1]]);if(type==="q")slide([[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]);if(type==="k"){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);if(cardState.kingReturn&&cardState.kingReturn.turns>0){const mode=cardState.kingReturn.mode;if(mode==="bn"||mode==="qn")[[2,1],[1,2],[-1,2],[-2,1],[-2,-1],[-1,-2],[1,-2],[2,-1]].forEach(([dr,dc])=>add(r+dr,c+dc,"kingReturn"));if(mode==="bn")slide([[1,1],[1,-1],[-1,1],[-1,-1]]);if(mode==="q"||mode==="qn")slide([[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]])}if(color==="w"&&r===7&&c===4&&!moved.wk){if(!moved.wrH&&board[7][5]===""&&board[7][6]===""&&board[7][7]==="wr")add(7,6,"castleKing");if(!moved.wrA&&board[7][1]===""&&board[7][2]===""&&board[7][3]===""&&board[7][0]==="wr")add(7,2,"castleQueen")}if(color==="b"&&r===0&&c===4&&!moved.bk){if(!moved.brH&&board[0][5]===""&&board[0][6]===""&&board[0][7]==="br")add(0,6,"castleKing");if(!moved.brA&&board[0][1]===""&&board[0][2]===""&&board[0][3]===""&&board[0][0]==="br")add(0,2,"castleQueen")}}return res}
  function getEqualityTargets(){if(cardState.activeMode!=="equalityPickB"||!cardState.selectedSquares[0])return[];const from=cardState.selectedSquares[0],moving=board[from.r]?.[from.c];if(!moving)return[];const result=[],row=from.r,color=moving[0];for(const dc of[-3,3]){const targetC=from.c+dc;if(targetC<0||targetC>7)continue;const target=board[row][targetC];if(!target||target[0]!==color)continue;const dir=Math.sign(dc);if(board[row][from.c+dir]||board[row][from.c+dir*2])continue;result.push({r:row,c:targetC,type:"equalityCastle"})}return result}
  function chooseEqualityFirst(r,c){const p=board[r]?.[c];if(!p||p[0]!==turn[0])return alert("내 기물만 선택 가능합니다.");cardState.selectedSquares=[{r,c}];cardState.activeMode="equalityPickB";selected={r,c};moves=getEqualityTargets();if(moves.length===0){alert("이 기물은 평등국가 캐슬링 가능한 상대 기물이 없습니다.");cardState.activeMode="equalityPickA";cardState.selectedSquares=[];selected=null;moves=[]}render()}
  function chooseEqualitySecond(r,c){const from=cardState.selectedSquares[0];if(!from){cardState.activeMode="equalityPickA";render();return}if(!getEqualityTargets().some(p=>p.r===r&&p.c===c))return alert("같은 가로줄에서 사이 빈칸 2칸인 내 기물만 선택 가능합니다.");applyEqualityCastleSpecial(from,{r,c});const usedColor=turn;cardState.activeMode=null;cardState.selectedSquares=[];selected=null;moves=[];equalityUses[usedColor]++;if(equalityUses[usedColor]>=10){if(localMode){alert("게임 끝! 승자: "+usedColor);renderCard();render();return}turn=turn==="white"?"black":"white";syncCardUpdate(true);renderCard();render();return}turn=turn==="white"?"black":"white";syncCardUpdate(true);renderCard();render()}
  function applyEqualityCastleSpecial(a,b){const row=a.r,pA=board[a.r][a.c],pB=board[b.r][b.c],dir=Math.sign(b.c-a.c),aFinalC=a.c+dir*2,bFinalC=a.c+dir;board[a.r][a.c]="";board[b.r][b.c]="";board[row][bFinalC]=pB;board[row][aFinalC]=pA}
  function syncCardUpdate(equalityUsed=false){if(!localMode&&ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:"cardUpdate",board,turn,enPassant,moved,necroCapturedPieces:cardState.necroCapturedPieces,kingReturn:cardState.kingReturn,reactionary:{active:cardState.reactionaryActive,rook:cardState.reactionaryRook,checks:cardState.reactionaryChecks},spaceTravelEnabled:cardState.spaceTravelEnabled,equalityUsed}))}
  function consumeCurrentCard(){const used=pendingCardUse||myCard;if(!used)return;if(!localMode&&ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:"card",card:used}));if(used===myCard)myCard=null;pendingCardUse=null;renderCard()}
  function getExorcismBishopOptions(){const result=[],color=turn[0];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(board[r][c]===color+"b")result.push({r,c});return result}
  function showExorcismModal(){const modal=document.getElementById("exorcismModal"),list=document.getElementById("exorcismList"),bishops=getExorcismBishopOptions();if(bishops.length===0){alert("사용할 수 있는 비숍이 없습니다.");cancelCardSelection();return}list.innerHTML="";bishops.forEach(pos=>{const btn=document.createElement("button");btn.className="selectBtn";btn.textContent=`비숍 ${squareName(pos.r,pos.c)}`;btn.onclick=()=>chooseExorcismBishop(pos.r,pos.c);list.appendChild(btn)});cardState.activeMode="exorcism";pendingCardUse=myCard;selected=null;moves=[];modal.classList.remove("hidden");render()}
  function chooseExorcismBishop(r,c){const p=board[r]?.[c];if(!p||p[0]!==turn[0]||p[1]!=="b")return alert("퇴마(물리)는 내 비숍만 사용할 수 있습니다.");closeAllCardModals();doExorcism(r,c);cardState.activeMode=null;selected=null;moves=[];consumeCurrentCard();syncCardUpdate();renderCard();render()}
  function doExorcism(r,c){const bishop=board[r][c];if(!bishop)return;const color=bishop[0],dir=color==="w"?-1:1;for(let dc=-1;dc<=1;dc++){const nr=r+dir,nc=c+dc;if(nr<0||nr>7||nc<0||nc>7)continue;const target=board[nr][nc];if(target&&target[1]==="k"){alert("퇴마(물리)로 킹 제거! 승자: "+turn);board[nr][nc]="";return}board[nr][nc]=""}turn=turn==="white"?"black":"white"}
  function getReactionaryOwnerColor(){return(!localMode&&myColor)?myColor:turn}
  function getReactionaryRookOptions(){const result=[],owner=getReactionaryOwnerColor();if(owner==="white"){if(moved.wk||moved.wrA||moved.wrH)return result;if(board[7]?.[0]==="wr")result.push({r:7,c:0});if(board[7]?.[7]==="wr")result.push({r:7,c:7})}if(owner==="black"){if(moved.bk||moved.brA||moved.brH)return result;if(board[0]?.[0]==="br")result.push({r:0,c:0});if(board[0]?.[7]==="br")result.push({r:0,c:7})}return result}
  function chooseReactionaryRook(r,c){const owner=getReactionaryOwnerColor(),p=board[r]?.[c];if(!p||p[0]!==owner[0]||p[1]!=="r")return alert("내 룩만 왕룩으로 선택 가능합니다.");if(!getReactionaryRookOptions().some(pos=>pos.r===r&&pos.c===c))return alert("캐슬링 둘 다 하지 않은 상태의 시작 위치 룩만 선택 가능합니다.");closeAllCardModals();cardState.reactionaryActive=true;cardState.reactionaryRook={r,c};cardState.reactionaryChecks=0;cardState.activeMode=null;selected=null;moves=[];syncCardUpdate();alert("왕룩 지정 완료. 이 룩이 잡히면 패배합니다.");renderCard();render()}
  function getSpaceTravelPieces(){if(!cardState.spaceTravelEnabled)return[];if(!localMode&&myColor&&turn!==myColor)return[];const color=turn[0],corners=color==="w"?[{r:0,c:0},{r:0,c:7}]:[{r:7,c:0},{r:7,c:7}],result=[];for(const pos of corners){const p=board[pos.r]?.[pos.c];if(p&&p[0]===color)result.push({r:pos.r,c:pos.c,type:"normal"})}return result}
  function getSpaceDestinationMoves(color){const result=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){const target=board[r][c];if(!target||target[0]!==color&&target[1]!=="k")result.push({r,c,type:"normal"})}return result}
  function showSpaceModal(){const modal=document.getElementById("spaceModal"),list=document.getElementById("spaceList"),targets=getSpaceTravelPieces();if(targets.length===0){alert("텔레포트 가능한 기물이 없습니다.");cancelCardSelection();return}list.innerHTML="";targets.forEach(pos=>{const piece=board[pos.r][pos.c],btn=document.createElement("button");btn.className="selectBtn";btn.textContent=`${pieceName(piece)} ${squareName(pos.r,pos.c)}`;btn.onclick=()=>chooseSpacePiece(pos.r,pos.c);list.appendChild(btn)});cardState.activeMode="spacePick";cardState.selectedSquares=[];selected=null;moves=targets;modal.classList.remove("hidden");render()}
  function chooseSpacePiece(r,c){const p=board[r]?.[c];if(!p||p[0]!==turn[0])return alert("텔레포트 가능한 내 기물만 선택 가능합니다.");if(!getSpaceTravelPieces().some(pos=>pos.r===r&&pos.c===c))return alert("상대 진영 코너에 도착한 기물만 선택 가능합니다.");closeAllCardModals();cardState.selectedSquares=[{r,c}];cardState.activeMode="spacePlace";selected={r,c};moves=getSpaceDestinationMoves(p[0]);alert("이동할 칸을 선택하세요. 상대 기물은 잡을 수 있지만 킹은 못 잡습니다.");renderCard();render()}
  function showNecroModal(){const modal=document.getElementById("necroModal"),list=document.getElementById("necroList");if(cardState.necroCapturedPieces.length===0){alert("부활시킬 수 있는 잡은 기물이 없습니다.");cancelCardSelection();return}list.innerHTML="";cardState.necroCapturedPieces.forEach((p,i)=>{const btn=document.createElement("button");btn.className="selectBtn";btn.textContent=`${pieceName(p)} (${p[0]==="w"?"백":"흑"})`;btn.onclick=()=>chooseNecroPiece(i);list.appendChild(btn)});cardState.activeMode="necroPick";pendingCardUse=myCard;selected=null;moves=[];modal.classList.remove("hidden");render()}
  function chooseNecroPiece(i){const p=cardState.necroCapturedPieces[i];if(!p)return alert("선택한 기물이 없습니다.");cardState.necroSelectedPiece=p;cardState.activeMode="necroPlace";moves=getNecroPlaceMoves();selected=null;closeAllCardModals();if(moves.length===0){alert("킹 주변에 부활 가능한 빈칸이 없습니다.");cardState.necroSelectedPiece=null;cardState.activeMode=null;moves=[];render();return}alert("킹 주변 빈칸을 선택하세요.");render()}
  function pieceName(p){return{p:"폰",r:"룩",n:"나이트",b:"비숍",q:"퀸",k:"킹"}[p?.[1]]||"알 수 없는 기물"}
  function findMyKing(){const k=turn==="white"?"wk":"bk";for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(board[r][c]===k)return{r,c};return null}
  function getNecroPlaceMoves(){const k=findMyKing();if(!k)return[];const result=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(dr===0&&dc===0)continue;const r=k.r+dr,c=k.c+dc;if(r<0||r>7||c<0||c>7)continue;if(!board[r][c])result.push({r,c,type:"normal"})}return result}
  function getKingReturnData(score){if(score>=3&&score<=6)return{mode:"bn",turns:15,score};if(score>=7&&score<=10)return{mode:"q",turns:5,score};if(score>=11&&score<=14)return{mode:"q",turns:10,score};if(score>=15&&score<=18)return{mode:"q",turns:15,score};if(score>=19&&score<=22)return{mode:"qn",turns:15,score};return null}
  function activateKingReturn(){const values={q:9,r:5,b:3,n:3};let score=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++){const p=board[r][c];if(!p||p[0]!==turn[0]||p[1]==="k"||p[1]==="p")continue;score+=values[p[1]]||0;board[r][c]=""}if(score>=23){alert("왕의 귀환 실패! 23점 이상이라 패배");if(!localMode&&ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:"resign"}));return}cardState.kingReturn=getKingReturnData(score);alert(cardState.kingReturn?`왕의 귀환 발동! 점수 ${score}, ${cardState.kingReturn.turns}턴 강화`:`왕의 귀환 발동! 점수 ${score}, 강화 없음`);turn=turn==="white"?"black":"white"}
  function renderCard(){const area=document.getElementById("cardArea");if(!area)return;const spaceTargets=getSpaceTravelPieces();if(cardState.activeMode==="equalityPickA"){area.innerHTML=`<div class="cardBox"><div class="cardTitle">평등국가</div><div class="cardDesc">캐슬링할 첫 번째 내 기물을 선택하세요.</div></div>`;return}if(cardState.activeMode==="equalityPickB"){area.innerHTML=`<div class="cardBox"><div class="cardTitle">평등국가</div><div class="cardDesc">사이에 빈칸 2칸이 있는 같은 가로줄의 내 기물을 선택하세요.</div></div>`;return}if(cardState.activeMode==="reactionaryPick"){area.innerHTML=`<div class="cardBox"><div class="cardTitle">반동분자</div><div class="cardDesc">왕룩으로 지정할 룩을 선택하세요.</div></div>`;return}if(cardState.activeMode==="exorcism"){area.innerHTML=`<div class="cardBox"><div class="cardTitle">퇴마(물리)</div><div class="cardDesc">능력을 사용할 비숍을 선택하세요.</div></div>`;return}if(cardState.activeMode==="necroPlace"){area.innerHTML=`<div class="cardBox"><div class="cardTitle">네크로맨서</div><div class="cardDesc">킹 주변 빈칸을 선택하세요.</div></div>`;return}if(cardState.activeMode==="spacePlace"){area.innerHTML=`<div class="cardBox"><div class="cardTitle">우주여행</div><div class="cardDesc">이동할 칸을 선택하세요. 상대 기물은 잡을 수 있지만 킹은 못 잡습니다.</div></div>`;return}if(cardState.reactionaryActive&&cardState.reactionaryRook){area.innerHTML=`<div class="cardBox"><div class="cardTitle">왕룩 활성화</div><div class="cardDesc">왕룩 위치: ${squareName(cardState.reactionaryRook.r,cardState.reactionaryRook.c)}<br>위협 누적: ${cardState.reactionaryChecks}/3</div></div>`;return}if(cardState.spaceTravelEnabled&&spaceTargets.length>0){area.innerHTML=`<div class="cardBox"><div class="cardTitle">우주여행 준비됨</div><div class="cardDesc">상대 진영 코너에 도착한 내 기물을 원하는 칸으로 텔레포트합니다.</div><button class="cardBtn" onclick="Game.activateSpaceTravel()">텔레포트 사용</button></div>`;return}if(!myCard){area.innerHTML="";return}if(myCard==="equality"){area.innerHTML=`<div class="cardBox"><div class="cardTitle">${getCardName(myCard)}</div><div class="cardDesc">${getCardDescription(myCard)}<br><b>사용 횟수 제한 없음</b></div><button class="cardBtn" onclick="Game.activateCard()">평등국가 사용</button></div>`;return}if(myCard==="reactionary"){area.innerHTML=`<div class="cardBox"><div class="cardTitle">${getCardName(myCard)}</div><div class="cardDesc">${getCardDescription(myCard)}<br><b>킹이 잡혔을 때 조건부 발동</b></div></div>`;return}area.innerHTML=`<div class="cardBox"><div class="cardTitle">${getCardName(myCard)}</div><div class="cardDesc">${getCardDescription(myCard)}</div><button class="cardBtn" onclick="Game.activateCard()">능력 사용</button></div>`}
  function activateSpaceTravel(){showSpaceModal()}
  function activateCard(){if(!myCard)return alert("사용할 카드가 없습니다.");const used=myCard;if(used==="equality"){const r=useCard(used,cardState);alert(r.message);selected=null;moves=[];renderCard();render();return}if(used==="reactionary"){alert("반동분자는 패시브 능력입니다. 내 킹이 잡혔을 때 조건을 만족하면 발동됩니다.");return}if(!localMode&&myColor&&turn!==myColor&&used==="doubleMove")return alert("더블무브는 내 턴에만 사용할 수 있습니다.");if(used==="exorcism"){pendingCardUse=used;showExorcismModal();return}if(used==="necro"){if(cardState.necroUsed)return alert("네크로맨서는 이미 사용했습니다.");if(cardState.necroCapturedPieces.length===0)return alert("아직 부활시킬 잡은 기물이 없습니다.");pendingCardUse=used;showNecroModal();return}if(used==="spaceTravel"){const r=useCard(used,cardState);if(!r.ok)return alert(r.message);alert(r.message);pendingCardUse=null;if(!localMode&&ws&&ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:"card",card:used}));syncCardUpdate();renderCard();render();return}if(used==="kingReturn"){pendingCardUse=used;activateKingReturn();consumeCurrentCard();syncCardUpdate();renderCard();render();return}if(used==="doubleMove"||used==="wildHorse"){const r=useCard(used,cardState);alert(r.message);if(!r.ok)return;pendingCardUse=used;consumeCurrentCard();renderCard();render();return}const r=useCard(used,cardState);alert(r.message);if(r.ok){pendingCardUse=used;consumeCurrentCard();renderCard();render()}}
  if(playerName)setTimeout(()=>{const i=document.getElementById("nicknameInput"),s=document.getElementById("loginStatus");if(i)i.value=playerName;if(s)s.textContent=`${playerName} 로그인됨`},0);
  return{startLocal,backMenu,resign,choosePromotion,activateCard,activateSpaceTravel,loginNickname,loginGoogle,createOnlineRoom,refreshRooms,joinByInviteCode,submitRoomPassword,cancelPasswordModal,copyInviteCode,cancelCardSelection,chooseExorcismBishop,chooseReactionaryRook,chooseSpacePiece,chooseNecroPiece}
})();
window.Game=Game;
